/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.HTMLValidator;
import exceptions.MalformedFileException;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christian
 */
public class ValidateHtmlView extends javax.swing.JFrame {

    private static ValidateHtmlView validarHtmlView;

    public ValidateHtmlView() {
        initComponents();
        defaultConfigurations();
    }

    private void showFileChooserView() {
        FileChooserView fileChooserView = FileChooserView.getFileChooserView();
        fileChooserView.setVisible(true);
    }

    private void defaultConfigurations() {
        setExtendedState(MAXIMIZED_BOTH);
        updateLabelFilePath("Nenhum arquivo selecionado", false);
        jPanelResults.setVisible(false);
    }

    public static ValidateHtmlView getValidarHtmlView() {
        if (validarHtmlView == null) {
            validarHtmlView = new ValidateHtmlView();
        }

        return validarHtmlView;
    }

    public void updateLabelFilePath(String filePath, boolean enableBtnAnalyzeHtml) {
        jLabelFilePath.setText(filePath);
        jBtnAnalyzeHtml.setEnabled(enableBtnAnalyzeHtml);
        clearResultInfo();
    }

    private void clearResultInfo() {
        DefaultTableModel tableModel = createDefaultTableModel();
        jTableTagsResult.setModel(tableModel);
        jPanelResults.setVisible(true);
        jPanelTable.setVisible(false);
        jResultText.setText("");
    }

    private DefaultTableModel createDefaultTableModel() {
        return new DefaultTableModel(new Object[]{"Tags", "Número de ocorrências"}, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInputAndButtons = new javax.swing.JPanel();
        jLabelFile = new javax.swing.JLabel();
        jLabelFilePath = new javax.swing.JLabel();
        jBtnFileChoose = new javax.swing.JButton();
        jBtnAnalyzeHtml = new javax.swing.JButton();
        jPanelResults = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jResultText = new javax.swing.JTextPane();
        jPanelTable = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableTagsResult = new javax.swing.JTable();
        jLabelWelcomeAnalyzeHtml = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFile.setText("Arquivo:");

        jLabelFilePath.setText("Nenhum arquivo selecionado.");

        jBtnFileChoose.setText("Selecionar Arquivo");
        jBtnFileChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnFileChooseMouseClicked(evt);
            }
        });
        jBtnFileChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFileChooseActionPerformed(evt);
            }
        });

        jBtnAnalyzeHtml.setText("Analisar HTML");
        jBtnAnalyzeHtml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAnalyzeHtmlMouseClicked(evt);
            }
        });
        jBtnAnalyzeHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnalyzeHtmlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInputAndButtonsLayout = new javax.swing.GroupLayout(jPanelInputAndButtons);
        jPanelInputAndButtons.setLayout(jPanelInputAndButtonsLayout);
        jPanelInputAndButtonsLayout.setHorizontalGroup(
            jPanelInputAndButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputAndButtonsLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBtnFileChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAnalyzeHtml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelInputAndButtonsLayout.setVerticalGroup(
            jPanelInputAndButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputAndButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInputAndButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFile)
                    .addComponent(jLabelFilePath)
                    .addComponent(jBtnFileChoose)
                    .addComponent(jBtnAnalyzeHtml))
                .addContainerGap())
        );

        jResultText.setEditable(false);
        jResultText.setFocusable(false);
        jScrollPane2.setViewportView(jResultText);

        jScrollPane4.setBorder(null);

        jTableTagsResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tag", "Número de ocorrências"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTagsResult.setFocusable(false);
        jTableTagsResult.setRequestFocusEnabled(false);
        jTableTagsResult.setRowSelectionAllowed(false);
        jTableTagsResult.getTableHeader().setResizingAllowed(false);
        jTableTagsResult.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTableTagsResult);

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTableLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4)
                    .addContainerGap()))
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
            .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTableLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelResultsLayout = new javax.swing.GroupLayout(jPanelResults);
        jPanelResults.setLayout(jPanelResultsLayout);
        jPanelResultsLayout.setHorizontalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelResultsLayout.setVerticalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultsLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelWelcomeAnalyzeHtml.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelWelcomeAnalyzeHtml.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcomeAnalyzeHtml.setText("Este é o Analisador de formatação de arquivos HTML! Para iniciar selecione um arquivo.");
        jLabelWelcomeAnalyzeHtml.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWelcomeAnalyzeHtml, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelResults, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInputAndButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelInputAndButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelWelcomeAnalyzeHtml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnFileChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFileChooseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFileChooseActionPerformed

    private void jBtnAnalyzeHtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnalyzeHtmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAnalyzeHtmlActionPerformed

    private void jBtnFileChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnFileChooseMouseClicked
        showFileChooserView();
        jLabelWelcomeAnalyzeHtml.setVisible(false);
        clearResultInfo();
    }//GEN-LAST:event_jBtnFileChooseMouseClicked

    private void jBtnAnalyzeHtmlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAnalyzeHtmlMouseClicked
        jPanelResults.setVisible(true);
        HTMLValidator validator = new HTMLValidator();
        File file = new File(jLabelFilePath.getText());

        try {
            boolean valid = validator.validateFile(file);
            if (valid) {
                jPanelTable.setVisible(true);
                jResultText.setText("Arquivo HTML bem formatado!\n");
                DefaultTableModel tableModel = createDefaultTableModel();
                jTableTagsResult.setModel(validator.insertTableRows(tableModel));
            }
        } catch (MalformedFileException e) {
            jPanelTable.setVisible(false);
            jResultText.setText(e.getMessage());
        } catch (Exception e) {
            jPanelTable.setVisible(false);
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro ao processar o arquivo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnAnalyzeHtmlMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnalyzeHtml;
    private javax.swing.JButton jBtnFileChoose;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JLabel jLabelFilePath;
    private javax.swing.JLabel jLabelWelcomeAnalyzeHtml;
    private javax.swing.JPanel jPanelInputAndButtons;
    private javax.swing.JPanel jPanelResults;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JTextPane jResultText;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableTagsResult;
    // End of variables declaration//GEN-END:variables
}
