/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.HTMLValidator;
import control.exceptions.ArquivoMalFormatadoException;
import java.io.File;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christian
 */
public class ValidarHtmlView extends javax.swing.JFrame {

    /**
     * Creates new form ValidarHtml
     */
    public ValidarHtmlView() {
        initComponents();
    }
    
    /**
     * Mostra a janela de adicionar uma nova entrada
     *
     */
    private void showFileChooserView() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Arquivos HTML", "html"));

        JFrame frame = new JFrame("Selecionar Arquivo");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setContentPane(fileChooser);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnFileChoose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTagsResult = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jResultText = new javax.swing.JTextPane();
        jFilePathText = new javax.swing.JTextField();
        jBtnAnalyzeHtml = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnFileChoose.setText("Selecionar Arquivo");
        jBtnFileChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnFileChooseMouseClicked(evt);
            }
        });
        jBtnFileChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFileChooseActionPerformed(evt);
            }
        });

        jTableTagsResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tag", "Número de ocorrências"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTagsResult);

        jLabel1.setText("Arquivo:");

        jResultText.setEditable(false);
        jScrollPane2.setViewportView(jResultText);

        jFilePathText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFilePathTextActionPerformed(evt);
            }
        });

        jBtnAnalyzeHtml.setText("Analisar HTML");
        jBtnAnalyzeHtml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAnalyzeHtmlMouseClicked(evt);
            }
        });
        jBtnAnalyzeHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnalyzeHtmlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFilePathText, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnFileChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAnalyzeHtml, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBtnFileChoose)
                    .addComponent(jFilePathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAnalyzeHtml))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnFileChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFileChooseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFileChooseActionPerformed

    private void jFilePathTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFilePathTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFilePathTextActionPerformed

    private void jBtnAnalyzeHtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnalyzeHtmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAnalyzeHtmlActionPerformed

    private void jBtnFileChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnFileChooseMouseClicked
//        jBtnFileChoose.setSelected(false);;
//        showFileChooserView();
        
    }//GEN-LAST:event_jBtnFileChooseMouseClicked

    private void jBtnAnalyzeHtmlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAnalyzeHtmlMouseClicked
        // TODO add your handling code here:
        HTMLValidator validador = new HTMLValidator();
        File arquivo = new File(jFilePathText.getText());
        
        try {
            boolean valido = validador.validarArquivo(arquivo);
            if (valido) {
                StringBuilder sb = new StringBuilder("Arquivo HTML bem formatado!\n");
//                sb.append("Tags encontradas: \n").append(validador.imprimirContador());
                
                jResultText.setText(sb.toString());
//                jTableTagsResult.
                DefaultTableModel tableModel = new DefaultTableModel();
                
                tableModel.addColumn("Tag");
                tableModel.addColumn("Número de ocorrências");
                
                Map<String, Integer> resultTags = validador.imprimirContador();
                resultTags.forEach((key, amount) -> {
                    tableModel.addRow(new Object[] {key, amount});
                });
                
                jTableTagsResult.setModel(tableModel);
                
//                for (Object[] row : rows) {
//                    tableModel.addRow(row);
//                };
                
            }
        } catch (ArquivoMalFormatadoException e) {
            jResultText.setText(e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro ao processar o arquivo", JOptionPane.ERROR_MESSAGE);
//            System.out.println("Erro ao processar o arquivo: " + e.getMessage());
        }
    }//GEN-LAST:event_jBtnAnalyzeHtmlMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidarHtmlView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidarHtmlView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidarHtmlView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidarHtmlView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidarHtmlView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnalyzeHtml;
    private javax.swing.JButton jBtnFileChoose;
    private javax.swing.JTextField jFilePathText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextPane jResultText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTagsResult;
    // End of variables declaration//GEN-END:variables
}
